### ISSUE TITLE
Sublime Text 3 Package control

### ISSUE THREAD

**Issue by BadDataBadData** [Jimbly/SublimeClipboardHistory#3]
I've only tried a couple of things, but it seems like this plugin works as is for ST3... I've installed it the old school way by pasting it from my ST2 directory, but it'd be great if you could get it working with Package Control for ST3 :)

**Comment by Jimbly** [comment]
Hi!  Sorry, didn't see this issue until just now!  Presumably due to changes in the ST3 beta, it seems like this no longer works drop-in in ST3 (getting errors like `ValueError: Edit objects may not be used after the TextCommand's run method has returned` when pasting from the menu).  It also doesn't seem to integrate with ST3's clipboard history for some reason, so I think I'd recommend just using the built in command `paste_from_history` and bind it to the key of your choice).

**Comment by BadDataBadData** [comment]
For the most part I was able to get it to work... I'd occasionally get errors printed to the console, but for the post part the plugin worked well. I didn't know about the built in function... It seems to work really well, but it's not as pretty because the menu it brings up is not colored with the theme's color like the quick select menu is... Oh well! Thanks for your response :)
