### ISSUE TITLE
Clear clipboard

### ISSUE THREAD

**Issue by mnakalay** [Jimbly/SublimeClipboardHistory#4]
Hello,
this works pretty nicely. One thing I miss though is the possibility to clear the clipboard.
Are you planning on implementing it?

**Comment by Jimbly** [comment]
I'd actually stopped using this plugin myself since moving to Sublime Text 3 which added a clipboard history (bind a key to 'paste_from_history'), though theirs is missing a couple minor features and doesn't always behave the way I'd like, so maybe it's worth porting over (should be simple) and getting into the new Package Control.  Adding a clear history would be relatively easy.

**Comment by Jimbly** [comment]
I've added a `jch_clear_history` command, you can find in in the command palette or bind it to a key of your choice =).  However, this module doesn't quite work on Sublime Text 3 Beta, and I'm not sure if I'll take the time to figure out how to make it work or not.
