### ISSUE TITLE
[Question] Why do we need SublimeClipboardHistory?

### ISSUE THREAD

**Issue by Kristinita** [Jimbly/SublimeClipboardHistory#7]
### 1. Briefly

I don't understood, why do we need SublimeClipboardHistory? Why do you develop it? May you add that information in `README.MD`?

### 2. Detail

1. SublimeClipboardHistory remember my copied text only if I copy text in Sublime Text files, but not in other programs. To remember text from other applications, I need to use system clipboard managers: for example, [**Clipdiary or Ditto**](http://softwarerecs.stackexchange.com/q/139/23324) in Windows.
2. What SublimeClipboardHistory have, what is not in the default Sublime Text settings? For `jch_paste_choice` command in native Sublime Text we have alternative: `paste_from_history` command — <kbd>Ctrl+K</kbd>, <kbd>Ctrl+V</kbd> for Windows.

Thanks.

**Comment by Jimbly** [comment]
For users of Sublime Text 2 (which this plugin was originally written for), there is no `paste_from_history`.

For Sublime Text 3 (still in beta), the most important reasons (to me) are already listed in the README: "Compared to the built-in command added in Sublime Text 3, this plugin uses a pop-up menu which respects your Sublime keybinds instead of an OS pop-up menu".  In Sublime I rebind my navigational keys to vi-styled navigational keys, and this respects those, whereas the built in `paste_from_history` requires you to use the arrow keys, which are annoying placed on most laptop keyboards.

Clipdiary or Ditto sound good, but are not cross-platform. I keep all of my Sublime settings/plugins synced between all of my development computers running on different OSes, and it's critical that they all behave exactly the same, or editing becomes incredibly frustrating.

As mentioned in the README, it also changes the cut and copy behaviors to better match what some people are used to from Visual Studio or Visual Assist: "Multiple sequential cuts will append to most recent clipboard entry" and "Full-line copy (when nothing is selected or an entire line is selected) pastes as full lines (similar to default Sublime/Visual Studio behaviors", although for some reason I think the latter might have also been added by default in Sublime Text 3, have not had a chance to try in a while =).

**Comment by Kristinita** [comment]
> Clipdiary or Ditto sound good, but are not cross-platform.

But we have [**similar gratis programs**](http://alternativeto.net/software/clipjump/?license=free) for other operation systems.

All right, I never used Visual Studio or Visual Assist, but I am little understood your reasons.

Thanks.
